config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.development?
  get "/read_xml" => "application#read_xml"
  match "/settings" => "application#settings", via: [:get, :post]
  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :roles
  resources :users
  resources :parts do 
    get :re_process
    get :req_body
  end
  resources :bom_headers do 
    get :re_process
    get :req_body
  end
  resources :documents do 
    get :re_process
    get :req_body
    
  end
  resources :document_uploads do 
    get :re_process
  end
  resources :xml_files do
    get :read_xml_files, on: :collection 
    resources :parts do 
      get :re_process
      get :req_body
    end
    resources :bom_headers do 
      get :re_process
      get :req_body
    end
    resources :bom_components
    resources :documents do 
      get :re_process
      get :req_body
      
    end
    resources :document_uploads do 
      get :re_process
    end
    get "/parts/view/:type" => "parts#index", as: :parts_by_type
    get "/bom_headers/view/:type" => "bom_headers#index", as: :bom_headers_by_type
    get "/documents/view/:type" => "documents#index", as: :documents_by_type
    get "/document_uploads/view/:type" => "document_uploads#index", as: :document_uploads_by_type
    get "/view/:type" => "xml_files#show", as: :xml_contents
  end
  get "/parts/view/:type" => "parts#index", as: :parts_by_type
  get "/bom_headers/view/:type" => "bom_headers#index", as: :bom_headers_by_type
  get "/documents/view/:type" => "documents#index", as: :documents_by_type
  get "/document_uploads/view/:type" => "document_uploads#index", as: :document_uploads_by_type
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :xml_file
  before_save :set_odo_body
  scope :inwork, -> {where(state: "INWORK")}
  scope :pending, -> {where.not(status: AppConstants::FILE_STATUS[:success])}
  scope :success, -> {where(status: AppConstants::FILE_STATUS[:success])}
  scope :added, -> {where(part_type: "AddedParts")}
  scope :changed, -> {where(part_type: "ChangedParts")}
  scope :unchanged, -> {where(part_type: "UnchangedParts")}
  scope :deleleted, -> {where(part_type: "DeletedParts")}

  def pending?
    status != AppConstants::FILE_STATUS[:success]
  end

  def success?
    status == AppConstants::FILE_STATUS[:success]
  end

  def self.load_parts(xml_file)
    json_obj = xml_file.json_obj
    if json_obj
      json_content = json_obj["COLLECTION"]
      transaction_obj = json_content["Release"]["Transaction"]
      ["AddedParts", "ChangedParts", "UnchangedParts", "DeletedParts"].each do |part_type|
        if json_content[part_type].present? && json_content[part_type]["Part"].present?
          parts = json_content[part_type]["Part"]
          parts = [parts] if parts.class.to_s != "Array"
          parts.each do |part|
            xml_file.parts.create(part_name: part["Name"], part_number: part["Number"], part_type: part_type, part_json: part, part_xml: part.to_xml(root: :Part), created_by: transaction_obj["CreatedBy"], transaction_obj: transaction_obj, state: part["State"])
          end
        end
      end
    end
  end

  def validate_part
    part = self.odoo_body.to_obj
    error = {}
    length = part.length.to_s.split(" ")[0].to_s.gsub("E", '')
    height = part.height.to_s.split(" ")[0].to_s.gsub("E", '')
    width = part.breadth.to_s.split(" ")[0].to_s.gsub("E", '')
    mass = (part.weight.present? ? part.weight.to_s[0...-2].strip : "").to_s.split(" ")[0].to_s.gsub("E", '')
    error[:classification_code] = true if part.classification_code.to_s.strip.blank?
    error[:part_number] = true if part.default_code.to_s.strip.blank?
    error[:part_name] = true if part.name.blank?
    error[:created_by] = true if part.created_by_from_api.blank?
    error[:updated_by] = true if part.updated_by_from_api.blank?
    error[:length] = true if length.present? && length.to_s.count("a-zA-Z") > 0
    error[:width] = true if width.present? && width.to_s.count("a-zA-Z") > 0
    error[:height] = true if height.present? && height.to_s.count("a-zA-Z") > 0
    error[:mass] = true if mass.present? && mass.to_s.count("a-zA-Z") > 0
    self.odoo_part_number = part.part
    self.error = error
  end

  def set_odo_body
    if self.id.blank?
      part = self.part_json.to_obj
      odoo_part_number = "#{part.CLASSIFICATION_CODE}#{part.Version}"
      body = {
        default_code: part.Number.to_s.strip,
        part: odoo_part_number,
        revision: part.Version,
        name: part.Name,
        part_type: part.PartType,
        material: part.MATERIAL,
        length: part.LENGTH,
        height: part.HEIGHT,
        breadth: part.WIDTH,
        weight: part.MASS.present? ? part.MASS.to_s[0...-2].strip : "",
        lifecycle_status: part.State,
        manufacturer: part.MANUFACTURER,
        manufacturer_ref: part.MANUFACTURER_REF,
        name_a: part.NAME_A,
        name_d: part.NAME_D,
        name_f: part.NAME_F,
        type: part.TYPE,
        classification_code: part.CLASSIFICATION_CODE,
        created_by_from_api: self.created_by,
        updated_by_from_api: part.LastChangedBy
      }
      self.odoo_part_number = odoo_part_number
      self.odoo_body = body
    end
    validate_part
  end

  def self.process_parts(xml_file)
    begin
      @setting = Setting.last
      parts = xml_file.parts.pending.where(error: {}).group_by(&:part_type)
      @odoo_service = OdooService.new(@setting, xml_file.id)
      added_parts = []
      added_parts = parts["AddedParts"].map { |e|  e.odoo_body } if parts["AddedParts"].present?
      other_parts = []
      other_parts = parts["ChangedParts"].map { |e|  e.odoo_body } if parts["ChangedParts"].present?
      other_parts += parts["UnchangedParts"].map { |e|  e.odoo_body } if parts["UnchangedParts"].present?
      deleleted_parts = parts["DeletedParts"].map { |e|  e.odoo_body["part"] } if parts["DeletedParts"].present?
      process_added_parts(xml_file.id, added_parts) if added_parts.present?
      process_other_parts(xml_file.id, other_parts) if other_parts.present?
      process_deleted_parts(xml_file.id, deleleted_parts) if deleleted_parts.present?
      "XML File parts processed"  
    rescue StandardError => e
      error = {
        error_type: "StandardError",
        title: e,
        message: e.message,
        backtrace: e.backtrace
      }
      HttpRequest.create(error: error, xml_file_id: xml_file.id)
    end
  end

  def self.process_added_parts(xml_file_id, parts, part_types=["AddedParts"], processed_by="Create Products")
    response, error = @odoo_service.create_products(parts)
    if error.present?
      Part.where(odoo_part_number: parts.map{|part| part["part"]}, part_type: part_types).update_all(status: AppConstants::FILE_STATUS[:failed], processed_by: processed_by, error: {server_error: error}, processed_by: processed_by, odoo_type: "Add")
    else
      create_parts = update_error_list(xml_file_id, parts.map{|part| part["part"]}, response, processed_by) if response.result.error_list.present?
      Part.where(odoo_part_number: create_parts, part_type: part_types).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: processed_by, odoo_type: "Add") if response.present? && response.error.blank? && create_parts.present?
    end
  end

  def self.process_other_parts(xml_file_id, parts)
    parts_to_be_updated = []
    added_parts = []
    existing_products = @odoo_service.get_products(parts.map{|part| part["part"]})
    existing_products.map { |product| product.default_code.to_s }
    parts.each do |part|
      if existing_products.include?(part["part"])
        parts_to_be_updated << part
      else
        added_parts << part
      end
    end
    process_added_parts(xml_file_id, added_parts, ["ChangedParts", "UnchangedParts"], "Created products by Update") if added_parts.present?
    if parts_to_be_updated.present?
      response, error = @odoo_service.update_products(parts_to_be_updated)
      if error.present?
        Part.where(odoo_part_number: parts_to_be_updated.map{|part| part["part"]}, part_type: ["ChangedParts", "UnchangedParts"]).update_all(status: AppConstants::FILE_STATUS[:failed], processed_by: "Update Products", error: {server_error: error})
      else
        update_parts = update_error_list(xml_file_id, parts_to_be_updated.map{|part| part["part"]}, response, "Update Products") if response.result.error_list.present?
        Part.where(odoo_part_number: update_parts, part_type: ["ChangedParts", "UnchangedParts"]).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "Update Products", odoo_type: "Update") if response.present? && response.error.blank? && update_parts.present?
      end
    end
  end

  def self.process_deleted_parts(xml_file_id, parts)
    response, error = @odoo_service.delete_products(parts)
    if error.present?
      Part.where(odoo_part_number: parts.map{|part| part["part"]}, part_type: "DeletedParts").update_all(status: AppConstants::FILE_STATUS[:failed], processed_by: "Delete Products", error: {server_error: error})
    else
      delete_parts = update_error_list(xml_file_id, parts.map{|part| part["part"]}, response, "Delete Products") if response.result.error_list.present?
      Part.where(odoo_part_number: delete_parts, part_type: "DeletedParts").update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "Delete Products") if response.present? && response.error.blank?
    end
  end

  def self.update_error_list(xml_file_id, parts, response, processed_by)
    error_parts = Part.where(xml_file_id: xml_file_id, part_number: response.result.error_list)
    new_parts = parts - error_parts.map { |e| e.odoo_part_number }
    parts_obj = {}
    error_parts.map { |e| parts_obj[e.part_number] = e }
    response.result.error_list.each_with_index do |error, i|
      error_msg = response.result.logs[i].to_s

      parts_obj[error]&.update(error: {server_error: error_msg}, processed_by: processed_by, status: AppConstants::FILE_STATUS[:success])
    end
    new_parts
  end

  def process_part
    if !self.error.present? || (self.error.present? && self.error["server_error"].present?)
      @setting = Setting.last
      @odoo_service = OdooService.new(@setting, self.xml_file_id)
      existing_products = @odoo_service.get_products([self.odoo_part_number])
      existing_products.map { |product| product.default_code.to_s }
      if self.part_type === "AddedParts" || !existing_products.include?(self.odoo_part_number)
        response, error = @odoo_service.create_products([self.odoo_body])
        if error
          self.update(status: AppConstants::FILE_STATUS[:failed], processed_by: "Create products#{ 'by Update' if self.part_type != 'AddedParts'}", error: {server_error: error}, odoo_type: "Add") if response.present?
        else
          parts = [self.odoo_part_number]
          parts = Part.update_error_list(self.xml_file_id, parts, response, processed_by) if response.result.error_list.present?
          self.update(status: AppConstants::FILE_STATUS[:success], processed_by: "Create products#{ 'by Update' if self.part_type != 'AddedParts'}", odoo_type: "Add", error: {}) if response.present? && parts.present?
        end
      elsif ["ChangedParts", "UnchangedParts"].include?(self.part_type)
        response, error = @odoo_service.update_products(parts_to_be_updated)
        if error
          self.update(status: AppConstants::FILE_STATUS[:failed], processed_by: "Update Products", odoo_type: "Update", error: {server_error: error}) if response.present?
        else
          parts = [self.odoo_part_number]

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :init_service!

  def index
    @xml_file, @parts = @service.index
  end

  def show
    @xml_file, @part = @service.show
  end

  def edit
    @xml_file, @part = @service.show
  end

  def update
    @xml_file, @part = @service.update
    redirect_to xml_file_parts_path(@part.xml_file_id)
  end

  def re_process
    @part = @service.re_process
    redirect_to xml_file_parts_path(@part.xml_file_id), alert: @part.error.present? ? "Something wrong in this part." : nil, notice: @part.error.blank? ? "Part reprocessed successfully." : nil
  end

  def destroy
    @service.destroy
    redirect_to xml_file_parts_path(@part.xml_file_id), notice: "Part Deleted"
  end

  def req_body
    @part, @body = @service.req_body
  end

  private
    def init_service!
      authorize(Part)
      @service = PartsService.new(request, params, current_user)
    end
end

app/views/parts/_edit.html.erb
<%= form_for([@xml_file, @part]) do |f|%>
  <div class="modal-header">
    <h4 class="modal-title">Part -
      <%= "#{@part.part_number} (#{@part.odoo_part_number})"%>
    </h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="row">
      <%= f.fields_for :odoo_body do |field|%>
        <%@part.odoo_body.each do |key, value|%>
          <div class="col-12 col-md-4">
            <div class="form-group">
              <label for=""><%=key.humanize%></label>
              <%= field.text_field key, value: value, class: "form-control #{'error-field' if @part.error[key]}"%>
            </div>
          </div>
        <% end -%>
      <% end -%>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Save", class: "btn btn-success"%>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>
<%end%>

app/views/parts/_index.html.erb
<div class="row">
  
  <div class="col-12 mb-2">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type].blank?%>" id="xml_file_details-tab" href='<%= @xml_file ? xml_file_parts_path(@xml_file) : parts_path%>' data-toggles="tab" data-targets="#xml_file_details" type="button" role="tab" aria-controls="home" aria-selected="true">All Parts</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'AddedParts'%>" id="parts-tab"  href='<%= @xml_file ? xml_file_parts_by_type_path(@xml_file, "AddedParts") : parts_by_type_path("AddedParts")%>' data-toggles="tab" data-targets="#parts" type="button" role="tab" aria-controls="parts" aria-selected="false">Added Parts</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'ChangedParts'%>" id="parts-tab"  href='<%= @xml_file ? xml_file_parts_by_type_path(@xml_file, "ChangedParts") : parts_by_type_path("ChangedParts")%>' data-toggles="tab" data-targets="#parts" type="button" role="tab" aria-controls="parts" aria-selected="false">Changed Parts</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'UnchangedParts'%>" id="parts-tab"  href='<%= @xml_file ? xml_file_parts_by_type_path(@xml_file, "UnchangedParts") : parts_by_type_path("UnchangedParts")%>' data-toggles="tab" data-targets="#parts" type="button" role="tab" aria-controls="parts" aria-selected="false">Unchanged Parts</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'DeletedParts'%>" id="parts-tab"  href='<%= @xml_file ? xml_file_parts_by_type_path(@xml_file, "DeletedParts") : parts_by_type_path("DeletedParts")%>' data-toggles="tab" data-targets="#parts" type="button" role="tab" aria-controls="parts" aria-selected="false">Deleted Parts</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active">
        <div class="row">
          <div class="col-12 no-padding" style="width:90%; ">
            <div class="row">
              <div class="col-12" >
                <%#= paginate @parts, theme: 'twitter-bootstrap-4', :pagination_class => "pagination justify-content-center" %>
                <table class="table table-bordered table-striped mb-3">
                  <thead>
                    <tr>
                      <th style="width: 5%;">S.No</th>
                      <th style="width: 15%;">Part Type</th>
                      <th style="width: 15%;">Windhicll PartNumber</th>
                      <th style="width: 15%;">Odoo Part Number</th>
                      <th style="width: 15%;">Part Name</th>
                      <th style="width: 15%;">Status</th>
                      <th style=""></th>
                    </tr>
                  </thead>
                  <tbody>
                    <%if @parts.present?%>
                      <%setting = Setting.last%>
                      <%i = current_page * AppConstants::RECORDS_PER_PAGE%>
                      <%@parts.each do |part|%>
                        <tr>
                          <td><%= i+= 1%></td>
                          <td><%= part.part_type%></td>
                          <td><%= part.part_number%></td>
                          <td><%= part.odoo_part_number%></td>
                          <td><%= part.odoo_body[setting.part_name_language]%></td>
                          <td><%= render "common/status", status: part.status%><% if part.error.present? && !part.success?%><%= render "common/error", message: part.error["server_error"].present? ? part.error["server_error"] : "#{part.error.keys.join(", ")} are required"%><%end%><br><span class="badge badge-secondary"><%= part.processed_by%></span></td>
                          <td>
                            <%if @xml_file%>
                              <%= link_to [@xml_file, part], class: "btn btn-info", remote: true do %>
                                <i class="fa fa-eye"></i>
                              <% end -%>
                              <%if policy(Part).write? && part.pending?%>
                                <%= link_to edit_xml_file_part_path(@xml_file, part), class: "btn btn-warning", remote: true do %>
                                  <i class="fa fa-edit"></i>
                                <% end -%>
                                <%= link_to xml_file_part_re_process_path(@xml_file, part), class: "btn btn-success" do %>
                                  <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
                                <% end -%>
                              <%end%>
                              <%= link_to xml_file_part_req_body_path(@xml_file, part), class: "btn btn-secondary", remote: true do %>
                                <i class="fas fa-code" aria-hidden="true"></i>
                              <% end -%>
                            <%else%>
                              <%= link_to part, class: "btn btn-info", remote: true do %>
                                <i class="fa fa-eye"></i>
                              <% end -%>
                              <%if policy(Part).write? && part.pending?%>
                                <%= link_to edit_part_path(part), class: "btn btn-warning", remote: true do %>
                                  <i class="fa fa-edit"></i>
                                <% end -%>
                                <%= link_to part_re_process_path(part), class: "btn btn-success" do %>
                                  <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
                                <% end -%>
                              <%end%>
                              <%= link_to part_req_body_path(part), class: "btn btn-secondary", remote: true do %>
                                <i class="fas fa-code" aria-hidden="true"></i>
                              <% end -%>
                            <% end -%>
                          </td>
                        </tr>
                      <%end%>
                    <%else%>
                      <tr>
                        <td colspan="6" class="text-danger text-center"><h4>No Parts Found!</h4></td>
                      </tr>
                    <% end -%>
                    
                  </tbody>
                </table>
                <%= paginate @parts, theme: 'twitter-bootstrap-4', :pagination_class => "pagination justify-content-center" %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/parts/_req_body.html.erb
<div class="modal-header">
  <h4 class="modal-title">Part -
    <%= "#{@part.part_number} (#{@part.odoo_part_number})"%> - Request Body
  </h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="row">
    <div class="col-12">
      <pre id="json-code">
      </pre>      
    </div>
  </div>
</div>
<div class="modal-footer">
  <%if @part.status != AppConstants::FILE_STATUS[:success]%>
    <%= link_to xml_file_part_re_process_path(@part.xml_file_id, @part), class: "btn btn-success" do %>
      <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
    <% end -%>
  <% end -%>
  <button class="btn btn-success" onclick="copyContent('json-code')">Copy Request Body</button>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/parts/_show.html.erb
<div class="modal-header">
  <h4 class="modal-title">Part -
    <%= "#{@part.part_number} (#{@part.odoo_part_number})"%>
  </h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="row">
    <%@part.odoo_body.each do |key, value|%>
    <div class="col-12 col-md-4">
      <div class="form-group">
        <label for=""><%=key.humanize%></label>
        <span class="form-control"><%=value%></span>
      </div>
    </div>
    <% end -%>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/parts/index.html.erb
<%page_name "Parts #{@xml_file&.file_name}"%>
<div class="card card-info m-0">
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <%= link_to xml_files_path, class: "btn btn-sm btn-info  mb-3 float-right" do %>
          <em class="fas fa-arrow-left"></em> Back
        <%end%>
        <h3>Parts <%=@xml_file&.file_name%></h3>
      </div>
      <div class="col-12 mb-2">
        <%if @xml_file%><%= render "common/file_header"%><% end -%>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active">
            <div class="row">
              <div class="col-12 no-padding" style="width:90%; ">
                <%= render "index"%>                
              </div>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/parts/show.js.erb
$("#common-modal-content").html("<%= j render "show"%>");
$('#common-modal').modal({show: true})