config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.development?
  get "/read_xml" => "application#read_xml"
  match "/settings" => "application#settings", via: [:get, :post]
  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :roles
  resources :users
  resources :parts do 
    get :re_process
    get :req_body
  end
  resources :bom_headers do 
    get :re_process
    get :req_body
  end
  resources :documents do 
    get :re_process
    get :req_body
    
  end
  resources :document_uploads do 
    get :re_process
  end
  resources :xml_files do
    get :read_xml_files, on: :collection 
    resources :parts do 
      get :re_process
      get :req_body
    end
    resources :bom_headers do 
      get :re_process
      get :req_body
    end
    resources :bom_components
    resources :documents do 
      get :re_process
      get :req_body
      
    end
    resources :document_uploads do 
      get :re_process
    end
    get "/parts/view/:type" => "parts#index", as: :parts_by_type
    get "/bom_headers/view/:type" => "bom_headers#index", as: :bom_headers_by_type
    get "/documents/view/:type" => "documents#index", as: :documents_by_type
    get "/document_uploads/view/:type" => "document_uploads#index", as: :document_uploads_by_type
    get "/view/:type" => "xml_files#show", as: :xml_contents
  end
  get "/parts/view/:type" => "parts#index", as: :parts_by_type
  get "/bom_headers/view/:type" => "bom_headers#index", as: :bom_headers_by_type
  get "/documents/view/:type" => "documents#index", as: :documents_by_type
  get "/document_uploads/view/:type" => "document_uploads#index", as: :document_uploads_by_type
end

app/models/bom_header.rb
class BomHeader < ApplicationRecord
	belongs_to :xml_file
	has_many :bom_components, dependent: :destroy

	scope :pending, -> { where.not(status: AppConstants::FILE_STATUS[:success]) }
  scope :success, -> { where(status: AppConstants::FILE_STATUS[:success]) }
  scope :added, -> { where(bom_type: "AddedBOMs") }
  scope :changed, -> { where(bom_type: "ChangedBOMs") }
  scope :unchanged, -> { where(bom_type: "UnchangedBOMs") }
  scope :deleted, -> { where(bom_type: "DeletedBOMs") }

  accepts_nested_attributes_for :bom_components, reject_if: :all_blank, allow_destroy: true

  def pending?
    status != AppConstants::FILE_STATUS[:success]
  end

	def self.load_bom_headers(xml_file)
		json_obj = xml_file.json_obj
    if json_obj
      json_content = json_obj["COLLECTION"]
      transaction_obj = json_content["Release"]["Transaction"]
      parts_json = xml_file.parts.pluck(:part_name, :odoo_part_number).to_h
      ["AddedBOMs", "ChangedBOMs", "UnchangedBOMs", "DeletedBOMs"].each do |type|
      	if json_content[type].present? && json_content[type]["BOMHeader"].present?
          bom_headers = json_content[type]["BOMHeader"]
          bom_headers = [bom_headers] if bom_headers.class.to_s != "Array"
          bom_headers.each do |bom_header|
            xml_file.bom_headers.create(bom_type: type, number: bom_header["Number"], json_obj: bom_header, xml_content: bom_header.to_xml(root: :BOMHeader), odoo_part_number: parts_json[bom_header["Number"]])
          end
        end
      end
    end
	end

	def self.process_boms(xml_file)
		begin
      @setting = Setting.last
      @xml_file = xml_file
			@odoo_service = OdooService.new(@setting, xml_file.id)
			added_bom_headers = xml_file.bom_headers.pending.added.includes(:bom_components)
			changed_bom_headers = xml_file.bom_headers.pending.includes(:bom_components).where(bom_type: ["ChangedBOMs", "UnchangedBOMs"])
			deleted_boms = xml_file.bom_headers.deleted
			process_added_boms(xml_file.id, added_bom_headers)		
			process_updated_boms(xml_file.id, changed_bom_headers)		
			process_deleted_boms(xml_file.id, deleted_boms)
		rescue StandardError => e
      error = {
        error_type: "StandardError",
        title: e,
        message: e.message,
        backtrace: e.backtrace
      }
      HttpRequest.create(error: error, xml_file_id: xml_file.id)
    end		
	end

	def self.process_bom(bom_header)
		@setting = Setting.last
		error = {}
		@odoo_service = OdooService.new(@setting, bom_header.xml_file_id)
		if bom_header.bom_type == "AddedBOMs"
			result = BomHeader.process_added_boms(bom_header.xml_file_id, [bom_header])
		elsif bom_header.bom_type != "DeletedBOMs"
			added_result, result = BomHeader.process_updated_boms(bom_header.xml_file_id, [bom_header])
		else
			result = BomHeader.process_deleted_boms(bom_header.xml_file_id, [bom_header])
		end
	end

	def self.process_added_boms(xml_file_id, bom_headers)
		boms = []
		if bom_headers.present?
			bom_component_ids = []
			del_bom_component_ids = []
			bom_header_ids = []
			bom_headers.each do |bom_header|
				bom_components = bom_header.bom_components.added
				deleted_components = bom_header.bom_components.deleted.where(part_state: "INWORK")
				empty_part_components = deleted_components.map { |comp| comp.part_number if comp.odoo_part_number.blank? }.compact
				odoo_part_numbers = {}
				if empty_part_components.present?
					search_result = @odoo_service.get_products(empty_part_components)
					search_result.each do |result|
						odoo_part_numbers[result.part] = result.default_code
					end
				end
				bom_components += deleted_components
				child_ids = []
				bom_components.each do |bom_component|
					odoo_part_number = bom_component.odoo_part_number || odoo_part_numbers[bom_component.part_number]
					if odoo_part_number.present?
						child_ids << {
							qty: bom_component.quantity,
							part: odoo_part_number
						}
						bom_component.update(odoo_part_number: odoo_part_number)
						if bom_component.bom_component_type === "DeletedBOMComponents"
							del_bom_component_ids << bom_component.id
						else
							bom_component_ids << bom_component.id
						end
					end
				end
				boms << {
					part: bom_header.odoo_part_number,
					child_ids: child_ids
				}
				bom_header_ids << bom_header.id
			end
			result, error = @odoo_service.create_boms(boms)
			if result.present?
				bom_header_ids, bom_component_ids, del_bom_component_ids = self.update_error_list(xml_file_id, [bom_header_ids, bom_component_ids, del_bom_component_ids], result, ["AddedBOMs", "AddedBOMComponents", "Added from DeletedBOMComponents"])
				BomHeader.where(id: bom_header_ids).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "AddedBOMs") if bom_header_ids.present?
				BomComponent.where(id: bom_component_ids).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "AddedBOMComponents", odoo_type: "Add") if bom_component_ids.present?
				BomComponent.where(id: del_bom_component_ids).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "Added from DeletedBOMComponents", odoo_type: "Add") if del_bom_component_ids.present?
			end
			result
		end
	end

	def self.process_updated_boms(xml_file_id, bom_headers)
		update_boms = []
		create_boms = []
		if bom_headers.present?
			bom_search_result = {}
			@odoo_service.search_boms(bom_headers.map { |e| e.odoo_part_number }).map { |result| 
				bom_search_result[result.part] ||= {}
				result.child_ids.map { |child| 
					bom_search_result[result.part][child.part] = child.qty
				}
			}
			bom_header_ids = []
			added_bom_header_ids = []
			error_comp_ids = []
			bom_component_ids = []
			added_component_ids = []
			bom_headers.each do |bom_header|
				bom = bom_header
				bom_components = bom_header.bom_components.where(bom_component_type: ["AddedBOMComponents", "ChangedBOMComponents", "UnchangedBOMComponents"])

				deleted_components = bom_header.bom_components.where(bom_component_type: "DeletedBOMComponents").where.not(part_state: "INWORK", odoo_part_number: nil)
				del_child_ids = deleted_components.pluck(:odoo_part_number).compact
				if bom.odoo_part_number && del_child_ids.present?
					delele_result = @odoo_service.delete_bom_components([bom.odoo_part_number], del_child_ids)
					if delele_result[1].present?
						deleted_components.update_all(error: {error: delele_result[1]})
						err = bom_header.error
						deleted_components.each do |comp|
							err[comp.odoo_part_number] = delele_result[1]
						end
						err["message"] = "#{err.keys} having the following error: #{delele_result[1]}"
						bom_header.update(error: err)
						error_comp_ids << bom_header.id
					else
						deleted_components.update_all(status: AppConstants::FILE_STATUS[:success])
					end
				end
				if bom.odoo_part_number.present?
					added_bom = {
						part: bom.odoo_part_number,
						child_ids: []
					}
					update_bom = {
						part: bom.odoo_part_number,
						child_ids: []
					}
					search_childs = bom_search_result[bom.odoo_part_number] || {}
					bom_components.each do |bom_component|
						search_child_quantity = search_childs[bom_component.odoo_part_number]
						if search_child_quantity.present?
							if bom_component.quantity != search_child_quantity
								update_bom[:child_ids] << {
									part: bom_component.odoo_part_number,
									qty: bom_component.quantity
								}
								bom_component_ids = bom_component.id
								bom_header_ids << bom_header.id
							end
						else
							added_bom[:child_ids] << {
								part: bom_component.odoo_part_number,
								qty: bom_component.quantity
							}
							added_bom_header_ids << bom_header.id
							added_component_ids << bom_component.id
						end
					end
					create_boms << added_bom if added_bom[:child_ids].present?
					update_boms << update_bom if update_bom[:child_ids].present?
					bom_header.update(status: AppConstants::FILE_STATUS[:success], processed_by: "UpdateBOMs", odoo_type: "Update") if !bom_components.present?
				end
			end
			if create_boms.present?
				add_result, error = @odoo_service.create_boms(create_boms)
				added_bom_header_ids = added_bom_header_ids - error_comp_ids
				added_bom_header_ids, added_component_ids, del_bom_component_ids = self.update_error_list(xml_file_id, [added_bom_header_ids, added_component_ids, []], add_result, ["Added by UpdateBOMs", "Added from UpdateBOMComponents", ""])
				BomHeader.where(id: added_bom_header_ids.uniq).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "Added by UpdateBOMs", odoo_type: "Add") if add_result && added_bom_header_ids.present?
				BomComponent.where(id: added_component_ids).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "Added from UpdateBOMComponents", odoo_type: "Add") if add_result && added_component_ids.present?
			end

			if update_boms.present?
				update_result, error = @odoo_service.update_boms(update_boms)
				bom_header_ids = bom_header_ids - error_comp_ids
				bom_header_ids, bom_component_ids, del_bom_component_ids = self.update_error_list(xml_file_id, [bom_header_ids, bom_component_ids, []], update_result, ["UpdateBOMs", "UpdateBOMComponents", ""])
				BomHeader.where(id: bom_header_ids.uniq).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "UpdateBOMs", odoo_type: "Update") if update_result && bom_header_ids.present?
				BomComponent.where(id: bom_component_ids).update_all(status: AppConstants::FILE_STATUS[:success], processed_by: "UpdateBOMComponents", odoo_type: "Update") if update_result && bom_component_ids.present?
			end
			[add_result, update_result]
		end
	end

	def self.process_deleted_boms(xml_file_id, bom_headers)
		if bom_headers.present?
			bom_components = BomComponent.deleted.where(bom_header_id: bom_headers.pluck(:id)).where.not(odoo_part_number: nil)
			result, error = @odoo_service.deleted_boms(bom_headers.pluck(:odoo_part_number).compact, bom_components.pluck(:odoo_part_number).compact)

app/controllers/bom_headers_controller.rb
class BomHeadersController < ApplicationController
  before_action :init_service!

  def index
    @xml_file, @bom_headers = @service.index
  end

  def show
    @xml_file, @bom_header, @bom_components = @service.show
  end

  def edit
    @xml_file, @bom_header, @bom_components = @service.show
  end

  def update
    @xml_file, @bom_header = @service.update
    redirect_to xml_file_bom_headers_path(@bom_header.xml_file_id)
  end

  def re_process
    @bom_header = @service.re_process
    redirect_to xml_file_bom_headers_path(@bom_header.xml_file_id), alert: @bom_header.error.present? ? "Something wrong in this BOM." : nil, notice: @bom_header.error.blank? ? "BOM reprocessed successfully." : nil
  end

  def destroy
    @service.destroy
    redirect_to xml_file_bom_headers_path(@bom_header.xml_file_id), notice: "BOM Deleted"
  end

  def req_body
    @bom_header, @body = @service.req_body
  end

  private
    def init_service!
      authorize(BomHeader)
      @service = BomHeadersService.new(request, params, current_user)
    end
end

app/views/bom_headers/_edit.html.erb
<%= form_for([@xml_file, @bom_header]) do |f|%>
  <div class="modal-header">
    <h4 class="modal-title">
      BOM - <%= "#{@bom_header.number} (#{@bom_header.odoo_part_number})"%>
    </h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="row">
      <div class="col-12">
        <div class="form-group">
          <label for="" class="text-bold">Part</label>
          <%= f.text_field :odoo_part_number, class: "form-control"%>
        </div>
      </div>
      <div class="col-12">
        <h5>Child ID's</h5>
        <table class="table table-striped table-bordered">
          <tr>
            <th>Type</th>
            <th>Part</th>
            <th>Qty</th>
            <th>Status</th>
          </tr>
          <%= f.fields_for :bom_components, @bom_components do |field|%>
            <%comp = field.object%>
            <tr>
              <td><%= comp.bom_component_type%></td>

            <%if comp.status === AppConstants::FILE_STATUS[:success]%>
                <td><%= comp.odoo_part_number%></td>
                <td><%= comp.quantity.to_s%></td>
                <td><%= render "common/status", status: comp.status%></td>
              
            <%else%>
              
                <td><%= field.text_field :odoo_part_number, class: "form-control"%></td>
                <td><%= field.text_field :quantity, class: "form-control"%></td>
                <td><%= render "common/status", status: comp.status%></td>
            <% end -%>
            </tr>
          <% end -%>
        </table>
      </div>
      
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Save", class: "btn btn-success"%>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>
<%end%>

app/views/bom_headers/_index.html.erb
<div class="row">
  
  <div class="col-12 mb-2">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type].blank?%>" id="xml_file_details-tab" href='<%= @xml_file ? xml_file_bom_headers_path(@xml_file) : bom_headers_path%>' data-toggles="tab" data-targets="#xml_file_details" type="button" role="tab" aria-controls="home" aria-selected="true">All BOMs</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'AddedBOMs'%>" id="BOMHeaders-tab"  href='<%= @xml_file ? xml_file_bom_headers_by_type_path(@xml_file, "AddedBOMs") : bom_headers_by_type_path("AddedBOMs")%>' data-toggles="tab" data-targets="#BOMHeaders" type="button" role="tab" aria-controls="BOMHeaders" aria-selected="false">Added BOMs</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'ChangedBOMs'%>" id="BOMs-tab"  href='<%= @xml_file ? xml_file_bom_headers_by_type_path(@xml_file, "ChangedBOMs") : bom_headers_by_type_path("ChangedBOMs")%>' data-toggles="tab" data-targets="#BOMHeaders" type="button" role="tab" aria-controls="BOMHeaders" aria-selected="false">Changed BOMs</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'UnchangedBOMs'%>" id="BOMHeaders-tab"  href='<%= @xml_file ? xml_file_bom_headers_by_type_path(@xml_file, "UnchangedBOMs") : bom_headers_by_type_path("UnchangedBOMs")%>' data-toggles="tab" data-targets="#BOMHeaders" type="button" role="tab" aria-controls="BOMHeaders" aria-selected="false">Unchanged BOMs</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'DeletedBOMs'%>" id="BOMHeaders-tab"  href='<%= @xml_file ? xml_file_bom_headers_by_type_path(@xml_file, "DeletedBOMs") : bom_headers_by_type_path("DeletedBOMs")%>' data-toggles="tab" data-targets="#parts" type="button" role="tab" aria-controls="parts" aria-selected="false">Deleted Boms</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active">
        <div class="row">
          <div class="col-12 no-padding" style="width:90%; ">
            <div class="row">
              <div class="col-12" >
                <%#= paginate @parts, theme: 'twitter-bootstrap-4', :pagination_class => "pagination justify-content-center" %>
                <table class="table table-bordered table-striped mb-3">
                  <thead>
                    <tr>
                      <th style="width: 5%;">S.No</th>
                      <th style="width: 15%;">BOM Type</th>
                      <th style="width: 15%;">BOM Number</th>
                      <th style="width: 15%;">Odoo BOM Number</th>
                      <th style="width: 15%;">Status</th>
                      <th style=""></th>
                    </tr>
                  </thead>
                  <tbody>
                    <%if @bom_headers.present?%>
                    <%i = current_page * AppConstants::RECORDS_PER_PAGE%>
                      <%@bom_headers.each do |bom_header|%>
                        <tr>
                          <td><%= i+= 1%></td>
                          <td><%= bom_header.bom_type%></td>
                          <td><%= bom_header.number%></td>
                          <td><%= bom_header.odoo_part_number%></td>
                          <td><%= render "common/status", status: bom_header.status%><% if bom_header.error.present?%><%= render "common/error", message: "#{bom_header.error["message"]} components having error"%><%end%></td>
                          <td>
                            <%if @xml_file%>
                              <%= link_to [@xml_file, bom_header], class: "btn btn-info", remote: true do %>
                                <i class="fa fa-eye"></i>
                              <% end -%>
                              <%if policy(BomHeader).write? && bom_header.pending?%>
                                <%= link_to edit_xml_file_bom_header_path(@xml_file, bom_header), class: "btn btn-warning", remote: true do %>
                                  <i class="fa fa-edit"></i>
                                <% end -%>
                                <%= link_to xml_file_bom_header_re_process_path(@xml_file, bom_header), class: "btn btn-success" do %>
                                  <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
                                <% end -%>
                              <%end%>
                              <%= link_to xml_file_bom_header_req_body_path(@xml_file, bom_header), class: "btn btn-secondary", remote: true do %>
                                <i class="fas fa-code" aria-hidden="true"></i>
                              <% end -%>
                            <%else%>
                              <%= link_to bom_header, class: "btn btn-info", remote: true do %>
                                <i class="fa fa-eye"></i>
                              <% end -%>
                              <%if policy(BomHeader).write? && bom_header.pending?%>
                                <%= link_to edit_bom_header_path(bom_header), class: "btn btn-warning", remote: true do %>
                                  <i class="fa fa-edit"></i>
                                <% end -%>
                                <%= link_to bom_header_re_process_path(bom_header), class: "btn btn-success" do %>
                                  <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
                                <% end -%>
                              <%end%>
                              <%= link_to bom_header_req_body_path(bom_header), class: "btn btn-secondary", remote: true do %>
                                <i class="fas fa-code" aria-hidden="true"></i>
                              <% end -%>
                            <% end -%>
                          </td>
                        </tr>
                      <%end%>
                    <%else%>
                      <tr>
                        <td colspan="6" class="text-danger text-center"><h4>No BOMs Found!</h4></td>
                      </tr>
                    <% end -%>
                    
                  </tbody>
                </table>
                <%= paginate @bom_headers, theme: 'twitter-bootstrap-4', :pagination_class => "pagination justify-content-center" %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/bom_headers/_req_body.html.erb
<div class="modal-header">
  <h4 class="modal-title">
    BOM - <%= "#{@bom_header.number} (#{@bom_header.odoo_part_number})"%>
  </h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="row">
    <div class="col-12">
      <pre id="json-code">
      </pre>      
    </div>
  </div>
</div>
<div class="modal-footer">
  <%if @bom_header.status != AppConstants::FILE_STATUS[:success]%>
    <%= link_to xml_file_bom_header_re_process_path(@bom_header.xml_file_id, @bom_header), class: "btn btn-success" do %>
      <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
    <% end -%>
  <% end -%>
  <button class="btn btn-success" onclick="copyContent('json-code')">Copy Request Body</button>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/bom_headers/_show.html.erb
<div class="modal-header">
  <h4 class="modal-title">
    BOM - <%= "#{@bom_header.number} (#{@bom_header.odoo_part_number})"%>
  </h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="row">
    <div class="col-12">
      <div class="form-group">
        <label for="" class="text-bold">Part</label>
        <span class="form-control"><%= @bom_header.odoo_part_number %></span>
      </div>
    </div>
    <div class="col-12">
      <label for="" class="text-bold">Childs</label>
      <table class="table table-striped table-bordered">
        <tr>
          <th>Type</th>
          <th>Part</th>
          <th>Qty</th>
          <th>Status</th>
        </tr>
        <%if @bom_components.present?%>
          <%@bom_components.each do |comp|%>
            <tr>
              <td><%= comp.bom_component_type%></td>
              <td><%= comp.odoo_part_number%></td>
              <td><%= comp.quantity.to_s%></td>
              <td><%= render "common/status", status: comp.status%><% if comp.error.present?%><%= render "common/error", message: "#{comp.error.values.join(", ")}"%><%end%></td>
            </tr>
          <% end -%>
        <%else%>
          <tr>
            <td colspan="2"><h5 class="text-danger">No childs found!</h5></td>
          </tr>
          
        <% end -%>
      </table>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/bom_headers/edit.js.erb
$("#common-modal-content").html("<%= j render "edit"%>");
$('#common-modal').modal({show: true})
$('[data-toggle="popover"]').popover()

app/views/bom_headers/index.html.erb
<%page_name "BOMs - #{@xml_file&.file_name}"%>

<div class="card card-info m-0">
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <%= link_to xml_files_path, class: "btn btn-sm btn-info  mb-3 float-right" do %>
          <em class="fas fa-arrow-left"></em> Back
        <%end%>
        <h3>BOMs <%=@xml_file&.file_name%></h3>
      </div>
      <div class="col-12 mb-2">
        <%= render "common/file_header"%>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active">
            <div class="row">
              <div class="col-12 no-padding" style="width:90%; ">
                <%= render "index"%>                
              </div>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/bom_headers/show.js.erb
$("#common-modal-content").html("<%= j render "show"%>");
$('#common-modal').modal({show: true})
$('[data-toggle="popover"]').popover()