config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.development?
  get "/read_xml" => "application#read_xml"
  match "/settings" => "application#settings", via: [:get, :post]
  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :roles
  resources :users
  resources :parts do 
    get :re_process
    get :req_body
  end
  resources :bom_headers do 
    get :re_process
    get :req_body
  end
  resources :documents do 
    get :re_process
    get :req_body
    
  end
  resources :document_uploads do 
    get :re_process
  end
  resources :xml_files do
    get :read_xml_files, on: :collection 
    resources :parts do 
      get :re_process
      get :req_body
    end
    resources :bom_headers do 
      get :re_process
      get :req_body
    end
    resources :bom_components
    resources :documents do 
      get :re_process
      get :req_body
      
    end
    resources :document_uploads do 
      get :re_process
    end
    get "/parts/view/:type" => "parts#index", as: :parts_by_type
    get "/bom_headers/view/:type" => "bom_headers#index", as: :bom_headers_by_type
    get "/documents/view/:type" => "documents#index", as: :documents_by_type
    get "/document_uploads/view/:type" => "document_uploads#index", as: :document_uploads_by_type
    get "/view/:type" => "xml_files#show", as: :xml_contents
  end
  get "/parts/view/:type" => "parts#index", as: :parts_by_type
  get "/bom_headers/view/:type" => "bom_headers#index", as: :bom_headers_by_type
  get "/documents/view/:type" => "documents#index", as: :documents_by_type
  get "/document_uploads/view/:type" => "document_uploads#index", as: :document_uploads_by_type
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :xml_file
  has_many :document_uploads, dependent: :destroy


  scope :pending, -> {where.not(status: AppConstants::FILE_STATUS[:success])}
  scope :success, -> {where(status: AppConstants::FILE_STATUS[:success])}
  scope :added, -> {where(doc_type: "AddedDocuments")}
  scope :changed, -> {where(doc_type: "ChangedDocuments")}
  scope :unchanged, -> {where(doc_type: "UnchangedDocuments")}
  scope :deleted, -> {where(doc_type: ["DeletedDocuments", "DeletedDocumentLinks"])}

  def deleted?
    ["DeletedDocuments", "DeletedDocumentLinks"].include?(doc_type)
  end

  def pending?
    status != AppConstants::FILE_STATUS[:success]
  end

  def success?
    status == AppConstants::FILE_STATUS[:success]
  end

  def self.load_documents(xml_file)
    json_obj = xml_file.json_obj
    if json_obj
      json_content = json_obj["COLLECTION"]
      @parts = nil
      @parts_number = nil
      @setting = nil
      @odoo_service = nil
      @xml_file_names = nil
      @document_names = nil
      @parts_search = nil
      @existing_documents = nil
      init_config(xml_file)
      ["AddedDocuments", "ChangedDocuments", "UnchangedDocuments", "DeletedDocuments", "DeletedDocumentLinks"].each do |type|
        if json_content[type].present? && (json_content[type]["Document"].present? || json_content[type]["DocumentLink"].present?)
          documents = json_content[type]["Document"] || json_content[type]["DocumentLink"]
          if documents.present?
            documents = [documents] if documents.class.to_s != "Array"
            documents.each do |document|
              doc = xml_file.documents.new(number: document["Number"] || document["AssociatedObjectNumber"], document_number: document["DocumentNumber"], name: document["Name"] || document["AssociatedObjectNumber"], doc_type: type, json_obj: document, xml_content: document.to_xml(root: :Document))
              doc = get_document_type(doc)
              doc = generate_part_number(doc)
              doc, document_url, new_file_name, old_file_name = generate_url(doc, doc.number)
              doc.save
              doc = process_create_document(xml_file, doc) if !["DeletedDocuments", "DeletedDocumentLinks"].include?(type)
            end
          end
        end
      end
    end
  end

  def self.init_config(xml_file, document=nil)
    @parts ||= xml_file.parts.pluck(:part_name, :odoo_part_number).to_h
    @parts_number ||= xml_file.parts.pluck(:part_number, :odoo_part_number).to_h
    @setting ||= Setting.last
    @odoo_service ||= OdooService.new(@setting, xml_file.id)
    @xml_file_names ||= xml_file.documents.pluck(:name).compact
    @document_names ||= document ? [document.name] : @xml_file_names
    @parts_search ||= @document_names.present? ? @odoo_service.get_products(@document_names).map { |part| [part.part, part.default_code] }.to_h : {}
    @existing_documents ||= @odoo_service.search_documents.map { |doc| [doc.document_number, doc.document_url] }.to_h
  end

  def self.process_documents(xml_file)
    begin
      # init_config(xml_file)
      process_create_documents(xml_file)
      process_delete_documents(xml_file)
    rescue StandardError => e
      error = {
        error_type: "StandardError",
        title: e,
        message: e.message,
        backtrace: e.backtrace
      }
      HttpRequest.create(error: error, xml_file_id: xml_file.id)
    end
  end

  def self.process_create_document(xml_file, document, process_to_odoo=false)
    # init_config(xml_file, document)
    odoo_document = {
      part_no: document.odoo_part_number,
      document_number: document.document_number,
      document_url: document.document_url,
      type: document.document_type
    }
    odoo_docs = []
    odoo_docs << odoo_document
    if document.odoo_part_number.present? && document.document_url.present? && document.document_number.present? && document.document_type.present?
      if @existing_documents[document.document_number].present? && @existing_documents[document.document_number] === odoo_document[:document_url]
        document.status = AppConstants::FILE_STATUS[:success]
        odoo_docs.delete(odoo_document)
      end
      if @setting.documents_folder.present? && document.odoo_part_number.present?
        docs = Dir.glob("#{@setting.documents_folder}/#{document.part_number}*.*")
        docs += Dir.glob("#{@setting.documents_folder}/#{document.odoo_part_number}*.*")
        docs.each do |doc|
          ext = File.extname(doc)

          if ext === ".dxf"
            odoo_document[:type] = "2d"
            get_doc_url(document, doc, true)
            odoo_document[:document_url] = @url.ext(".dxf")
            unless @existing_documents[document.document_number].present? && @existing_documents[document.document_number] === odoo_document[:document_url]
              odoo_docs << odoo_document
            end
          end
          new_file_name = doc.include?(document.odoo_part_number) ? doc : doc.gsub(document.part_number, document.odoo_part_number)
          File.rename(doc, new_file_name) unless doc.include?(document.odoo_part_number)
          ext = File.extname(new_file_name)
          ProcessDocumentUploadJob.perform_later(document.id, new_file_name)
          # upload_document(document.id, new_file_name)
          # upload_document(document.id, new_file_name, true) if [".jpg", ".jpeg"].include?(ext.downcase)
        end
      end
    else
      error = []
      error << "odoo part number" if document.odoo_part_number.blank?
      error << "document url" if document.document_url
      error << "document number" if document.document_number
      error << "document type" if document.document_type
      document.error = {message: "#{error.join(",")} are missing"}

    end
    document.odoo_body = { document_list: odoo_docs.uniq }
    document.save
    document
  end

  def self.upload_to_server(xml_file, document_ids, odoo_documents, document=nil)
    if odoo_documents.present?
      init_config(xml_file, document) if document
      result, error = @odoo_service.create_documents(odoo_documents)
      document_ids = handle_error(xml_file, document_ids, result)
      xml_file.documents.where(id: document_ids).update_all(status: AppConstants::FILE_STATUS[:success], odoo_type: "Add", error: {}) if result.present? && document_ids.present?
    end
  end

  def self.handle_error(xml_file, document_ids, response)
    if response.result.present? && response.result.error_list.present?
      response.result.error_list.each_with_index do |part_number, ind|
        doc = xml_file.documents.pending.where.not(doc_type: ["DeletedDocuments", "DeletedDocumentLinks"]).find_by(odoo_part_number: part_number)
        doc.update(status: AppConstants::FILE_STATUS[:failed], error: {message: response.result.logs[ind]}) if doc
        document_ids.delete doc.id
      end
    end
    document_ids
  end

  def self.process_create_documents(xml_file)
    @document_ids = []
    @odoo_documents = []
    init_config(xml_file)
    xml_file.documents.pending.where.not(doc_type: ["DeletedDocuments", "DeletedDocumentLinks"]).each do |document|
      @odoo_documents += document.odoo_body["document_list"] if document.odoo_body.present? && document.odoo_body["document_list"].present? && document.document_url.present?
      @document_ids << document.id if document.odoo_body.present? && document.odoo_body["document_list"].present? && document.document_url.present?
    end
    upload_to_server(xml_file, @document_ids, @odoo_documents.uniq) if @odoo_documents.present?
      
  end

  def self.process_delete_document(xml_file, document, process_to_odoo=false)
    init_config(xml_file, document) if process_to_odoo
    @document_ids ||= []
    @odoo_documents ||= []
    document = generate_part_number(document, true)
    @odoo_documents << document.odoo_part_number if document.odoo_part_number.present?
    @document_ids << document.id if document.odoo_part_number.present?
    document.save
    if process_to_odoo && @odoo_documents.present?
      result = @odoo_service.delete_documents(@odoo_documents)
      document.update(status: AppConstants::FILE_STATUS[:success], odoo_type: "Delete") if result.present?
    end
  end

  def self.process_delete_documents(xml_file)
    @document_ids = []
    @odoo_documents = []
    xml_file.documents.pending.deleted.each do |document|
      process_delete_document(xml_file, document)
    end
    if @odoo_documents.present?
      result = @odoo_service.delete_documents(@odoo_documents)
      xml_file.documents.where(id: document_ids).update_all(status: AppConstants::FILE_STATUS[:success], odoo_type: "Delete") if result.present? && @document_ids.present?
    end
  end

  def self.get_part_number(name, by_number=false)
    (by_number ? @parts_number[name] : @parts[name]) || @parts_search[name]
  end

  def self.generate_part_number(document, by_number=false)
    new_part_number = part_number = nil
    if document.name.present?
      if document.name.to_s.include?("_")
        name = document.name.split("_")[0]
        part_number = get_part_number(name, by_number)
        new_part_number = part_number ? "#{part_number}_#{document.name.split("_")[1]}" : nil
      else
        part_number = new_part_number = get_part_number(document.name, by_number)
      end
    end
    document.part_number = document.name.to_s.split("_")[0]
    document.odoo_part_number = part_number
    document.document_number = new_part_number
    document
  end

  def self.get_doc_url(document, old_file_name, from_doc=false)
    url = nil
    if document.odoo_part_number.present? && old_file_name.present?
      @ext = File.extname(old_file_name)
      @old_file_name_without_ext = File.basename(old_file_name, @ext)
      @new_file_name_without_ext = @setting.rename_document && !from_doc ? document.odoo_part_number : @old_file_name_without_ext
      @new_file_name = "#{@new_file_name_without_ext}#{@ext}"
      if [".ASM", ".PRT"].include?(@ext)

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :init_service!

  def index
    @xml_file, @documents = @service.index
  end

  def show
    @xml_file, @document = @service.show
  end

  def edit
    @xml_file, @document = @service.edit
  end

  def update
    @xml_file, @document = @service.update
    redirect_to xml_file_documents_path(@document.xml_file_id)
  end

  def re_process
    @document = @service.re_process
    redirect_to xml_file_documents_path(@document.xml_file_id), alert: @document.error.present? ? "Something wrong in this Document." : nil, notice: @document.error.blank? ? "Document reprocessed successfully." : nil
  end

  def destroy
    @service.destroy
    redirect_to xml_file_documents_path(@document.xml_file_id), notice: "Document Deleted"
  end

  def req_body
    @document, @body = @service.req_body
  end

  private
    def init_service!
      authorize(Document)
      @service = DocumentsService.new(request, params, current_user)
    end
end

app/views/documents/_edit.html.erb
<%= form_for([@xml_file, @document]) do |f|%>
  <div class="modal-header">
    <h4 class="modal-title">Documents -
      <%= "#{@document.number} - #{@document.document_number}"%>
    </h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="row">
      <div class="col-6">
        <div class="form-group">
          <%= f.label :odoo_part_number, "Part No"%>
          <%= f.text_field :odoo_part_number, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="col-6">
        <div class="form-group">
          <%= f.label :document_number%>
          <%= f.text_field :document_number, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="col-6">
        <div class="form-group">
          <%= f.label :document_url%>
          <%= f.url_field :document_url, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="col-6">
        <div class="form-group">
          <%= f.label :document_type%>
          <%= f.text_field :document_type, required: true, class: "form-control"%>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Save", class: "btn btn-success"%>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>
<%end%>

app/views/documents/_index.html.erb
<div class="row">
  
  <div class="col-12 mb-2">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type].blank?%>" id="xml_file_details-tab" href='<%= @xml_file ? xml_file_documents_path(@xml_file) : documents_path()%>' data-toggles="tab" data-targets="#xml_file_details" type="button" role="tab" aria-controls="home" aria-selected="true">All Documents</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'AddedDocuments'%>" id="BOMHeaders-tab"  href='<%= @xml_file ? xml_file_documents_by_type_path(@xml_file, "AddedDocuments") : documents_by_type_path("AddedDocuments")%>' data-toggles="tab" data-targets="#BOMHeaders" type="button" role="tab" aria-controls="BOMHeaders" aria-selected="false">Added Documents</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'ChangedDocuments'%>" id="Documents-tab"  href='<%= @xml_file ? xml_file_documents_by_type_path(@xml_file, "ChangedDocuments") : documents_by_type_path("ChangedDocuments")%>' data-toggles="tab" data-targets="#BOMHeaders" type="button" role="tab" aria-controls="BOMHeaders" aria-selected="false">Changed Documents</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'UnchangedDocuments'%>" id="BOMHeaders-tab"  href='<%= @xml_file ? xml_file_documents_by_type_path(@xml_file, "UnchangedDocuments") : documents_by_type_path("UnchangedDocuments")%>' data-toggles="tab" data-targets="#BOMHeaders" type="button" role="tab" aria-controls="BOMHeaders" aria-selected="false">Unchanged Documents</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= 'active' if params[:type] === 'DeletedDocuments'%>" id="BOMHeaders-tab"  href='<%= @xml_file ? xml_file_documents_by_type_path(@xml_file, "DeletedDocuments") : documents_by_type_path("DeletedDocuments")%>' data-toggles="tab" data-targets="#parts" type="button" role="tab" aria-controls="parts" aria-selected="false">Deleted Documents</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active">
        <div class="row">
          <div class="col-12 no-padding" style="width:90%; ">
            <div class="row">
              <div class="col-12" >
                <%#= paginate @parts, theme: 'twitter-bootstrap-4', :pagination_class => "pagination justify-content-center" %>
                <table class="table table-bordered table-striped mb-3">
                  <thead>
                    <tr>
                      <th style="width: 5%;">S.No</th>
                      <th style="width: 10%;">Document Type</th>
                      <th style="width: 5%;">Name</th>
                      <th style="width: 10%;">Number</th>
                      <th style="width: 10%;">Document Number</th>
                      <th style="width: 10%;">Odoo Part Number</th>
                      <th style="width: 20%;">Document URL</th>
                      <th style="width: 15%;">Status</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <%if @documents.present?%>
                      <%i = current_page * AppConstants::RECORDS_PER_PAGE%>
                      <%@documents.each do |document|%>
                        <tr>
                          <td><%= i+= 1%></td>
                          <td><%= document.doc_type%></td>
                          <td><%= document.name%></td>
                          <td><%= document.number%></td>
                          <td><%= document.document_number%></td>
                          <td><%= document.odoo_part_number%></td>
                          <td><%= document.document_url%></td>
                          <td>
                            <%= render "common/status", status: document.status%><% if document.error.present?%><%= render "common/error", message: "#{document.error["message"]}"%><%end%>
                          </td>
                          <td>
                            <%if @xml_file%>
                              <%if policy(Document).write? && document.pending?%>
                                <%= link_to edit_xml_file_document_path(@xml_file, document), class: "btn btn-warning", remote: true do %>
                                  <i class="fa fa-edit"></i>
                                <% end -%>
                                <%= link_to xml_file_document_re_process_path(@xml_file, document), class: "btn btn-success" do %>
                                  <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
                                <% end -%>
                              <%end%>
                              <%= link_to xml_file_document_req_body_path(@xml_file, document), class: "btn btn-secondary", remote: true do %>
                                <i class="fas fa-code" aria-hidden="true"></i>
                              <% end -%>
                            <%else%>
                              <%if policy(Document).write? && document.pending?%>
                                <%= link_to edit_document_path(document), class: "btn btn-warning", remote: true do %>
                                  <i class="fa fa-edit"></i>
                                <% end -%>
                                <%= link_to document_re_process_path(document), class: "btn btn-success" do %>
                                  <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
                                <% end -%>
                              <%end%>
                              <%= link_to document_req_body_path(document), class: "btn btn-secondary", remote: true do %>
                                <i class="fas fa-code" aria-hidden="true"></i>
                              <% end -%>
                            <% end -%>
                              
                          </td>
                        </tr>
                      <%end%>
                    <%else%>
                      <tr>
                        <td colspan="6" class="text-danger text-center"><h4>No Documents Found!</h4></td>
                      </tr>
                    <% end -%>
                    
                  </tbody>
                </table>
                <%= paginate @documents, theme: 'twitter-bootstrap-4', :pagination_class => "pagination justify-content-center" %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/documents/_req_body.html.erb
<div class="modal-header">
  <h4 class="modal-title">Documents -
    <%= "#{@document.document_number} (#{@document.name})"%> - Request Body
  </h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="row">
    <div class="col-12">
      <pre id="json-code">
      </pre>      
    </div>
  </div>
</div>
<div class="modal-footer">
  <%if @document.status != AppConstants::FILE_STATUS[:success]%>
    <%= link_to xml_file_document_re_process_path(@document.xml_file_id, @document), class: "btn btn-success" do %>
      <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
    <% end -%>
  <% end -%>
  <button class="btn btn-success" onclick="copyContent('json-code')">Copy Request Body</button>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/documents/edit.js.erb
$("#common-modal-content").html("<%= j render "edit"%>");
$('#common-modal').modal({show: true})

app/views/documents/index.html.erb
<%page_name "Documents #{@xml_file&.file_name}"%>

<div class="card card-info m-0">
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <%= link_to xml_files_path, class: "btn btn-sm btn-info  mb-3 float-right" do %>
          <em class="fas fa-arrow-left"></em> Back
        <%end%>
        <h3>Documents <%=@xml_file&.file_name%></h3>
      </div>
      <div class="col-12 mb-2">
        <%= render "common/file_header"%>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active">
            <div class="row">
              <div class="col-12 no-padding" style="width:90%; ">
                <%= render "index"%>                
              </div>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/documents/req_body.js.erb
$("#common-modal-content").html("<%= j render "req_body"%>");
$("#json-code").html(JSON.stringify(<%= @body.html_safe%>, null, 4))
$('#common-modal').modal({show: true})