config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.development?
  get "/read_xml" => "application#read_xml"
  match "/settings" => "application#settings", via: [:get, :post]
  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :roles
  resources :users
  resources :parts do 
    get :re_process
    get :req_body
  end
  resources :bom_headers do 
    get :re_process
    get :req_body
  end
  resources :documents do 
    get :re_process
    get :req_body
    
  end
  resources :document_uploads do 
    get :re_process
  end
  resources :xml_files do
    get :read_xml_files, on: :collection 
    resources :parts do 
      get :re_process
      get :req_body
    end
    resources :bom_headers do 
      get :re_process
      get :req_body
    end
    resources :bom_components
    resources :documents do 
      get :re_process
      get :req_body
      
    end
    resources :document_uploads do 
      get :re_process
    end
    get "/parts/view/:type" => "parts#index", as: :parts_by_type
    get "/bom_headers/view/:type" => "bom_headers#index", as: :bom_headers_by_type
    get "/documents/view/:type" => "documents#index", as: :documents_by_type
    get "/document_uploads/view/:type" => "document_uploads#index", as: :document_uploads_by_type
    get "/view/:type" => "xml_files#show", as: :xml_contents
  end
  get "/parts/view/:type" => "parts#index", as: :parts_by_type
  get "/bom_headers/view/:type" => "bom_headers#index", as: :bom_headers_by_type
  get "/documents/view/:type" => "documents#index", as: :documents_by_type
  get "/document_uploads/view/:type" => "document_uploads#index", as: :document_uploads_by_type
end

app/views/layouts/partials/_header.html.erb
<header class="topnavbar-wrapper">
   <!-- top navbar-->
   <!-- START Top Navbar-->
   <nav class="navbar topnavbar">
      <!-- START navbar header-->
      <div class="navbar-header" style="background: white;"><a class="navbar-brand" href="/">
            <div class="brand-logo" style="padding: 0;"><img class="img-fluid" src="/logo.jpg" alt="App Logo" style="width: 100%; height: 50px"></div>
            <div class="brand-logo-collapsed" style="padding: 0;"><img class="img-fluid" src="/logo.jpg" alt="App Logo" style="width: 100%; height: 50px"></div>
         </a></div><!-- END navbar header-->
      <!-- START Left navbar-->
      <ul class="navbar-nav mr-auto flex-row">
         <li class="nav-item">
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops--><a class="nav-link d-none d-md-block d-lg-block d-xl-block" href="#" data-trigger-resize="" data-toggle-state="aside-collapsed"><em class="fas fa-bars"></em></a><!-- Button to show/hide the sidebar on mobile. Visible on mobile only.--><a class="nav-link sidebar-toggle d-md-none" href="#" data-toggle-state="aside-toggled" data-no-persist="true"><em class="fas fa-bars"></em></a>
         </li><!-- START User avatar toggle-->
         <li class="nav-item d-none d-md-block">
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops--><a class="nav-link" id="user-block-toggle" href="#user-block" data-toggle="collapse"><em class="icon-user"></em></a>
         </li><!-- END User avatar toggle-->
         
      </ul><!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="navbar-nav flex-row">
         <!-- Search icon-->
         <li class="nav-item">
            <div class="alert alert-success m-1" id="file_processing_alert">asdf</div>
         </li>
         <li class="nav-item">
            <%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %>
               <em class="fas fa-sign-out-alt"></em> Logout
            <%end%>
         </li><!-- Fullscreen (only desktops)-->
         
      </ul><!-- END Right Navbar-->
</header>

app/views/layouts/partials/_right_sidebar.html.erb
<!-- offsidebar-->
<aside class="offsidebar d-none">
   <!-- START Off Sidebar (right)-->
   <nav>
      <div role="tabpanel">
         <!-- Nav tabs-->
         <ul class="nav nav-tabs nav-justified" role="tablist">
            <li class="nav-item" role="presentation"><a class="nav-link active" href="#app-settings" aria-controls="app-settings" role="tab" data-toggle="tab"><em class="icon-equalizer fa-lg"></em></a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="#app-chat" aria-controls="app-chat" role="tab" data-toggle="tab"><em class="icon-user fa-lg"></em></a></li>
         </ul><!-- Tab panes-->
         <div class="tab-content">
            <div class="tab-pane fade active show" id="app-settings" role="tabpanel">
               <h3 class="text-center text-thin mt-4">Settings</h3>
               <div class="p-2">
                  <h4 class="text-muted text-thin">Themes</h4>
                  <div class="row row-flush mb-2">
                     <div class="col mb-2">
                        <div class="setting-color"><label data-load-css="/templates/admin/css/theme-a.css"><input type="radio" name="setting-theme" checked="checked"><span class="icon-check"></span><span class="split"><span class="color bg-info"></span><span class="color bg-info-light"></span></span><span class="color bg-white"></span></label></div>
                     </div>
                     <div class="col mb-2">
                        <div class="setting-color"><label data-load-css="/templates/admin/css/theme-b.css"><input type="radio" name="setting-theme"><span class="icon-check"></span><span class="split"><span class="color bg-green"></span><span class="color bg-green-light"></span></span><span class="color bg-white"></span></label></div>
                     </div>
                     <div class="col mb-2">
                        <div class="setting-color"><label data-load-css="/templates/admin/css/theme-c.css"><input type="radio" name="setting-theme"><span class="icon-check"></span><span class="split"><span class="color bg-purple"></span><span class="color bg-purple-light"></span></span><span class="color bg-white"></span></label></div>
                     </div>
                     <div class="col mb-2">
                        <div class="setting-color"><label data-load-css="/templates/admin/css/theme-d.css"><input type="radio" name="setting-theme"><span class="icon-check"></span><span class="split"><span class="color bg-danger"></span><span class="color bg-danger-light"></span></span><span class="color bg-white"></span></label></div>
                     </div>
                  </div>
                  <div class="row row-flush mb-2">
                     <div class="col mb-2">
                        <div class="setting-color"><label data-load-css="/templates/admin/css/theme-e.css"><input type="radio" name="setting-theme"><span class="icon-check"></span><span class="split"><span class="color bg-info-dark"></span><span class="color bg-info"></span></span><span class="color bg-gray-dark"></span></label></div>
                     </div>
                     <div class="col mb-2">
                        <div class="setting-color"><label data-load-css="/templates/admin/css/theme-f.css"><input type="radio" name="setting-theme"><span class="icon-check"></span><span class="split"><span class="color bg-green-dark"></span><span class="color bg-green"></span></span><span class="color bg-gray-dark"></span></label></div>
                     </div>
                     <div class="col mb-2">
                        <div class="setting-color"><label data-load-css="/templates/admin/css/theme-g.css"><input type="radio" name="setting-theme"><span class="icon-check"></span><span class="split"><span class="color bg-purple-dark"></span><span class="color bg-purple"></span></span><span class="color bg-gray-dark"></span></label></div>
                     </div>
                     <div class="col mb-2">
                        <div class="setting-color"><label data-load-css="/templates/admin/css/theme-h.css"><input type="radio" name="setting-theme"><span class="icon-check"></span><span class="split"><span class="color bg-danger-dark"></span><span class="color bg-danger"></span></span><span class="color bg-gray-dark"></span></label></div>
                     </div>
                  </div>
               </div>
               <div class="p-2">
                  <h4 class="text-muted text-thin">Layout</h4>
                  <div class="clearfix">
                     <p class="float-left">Fixed</p>
                     <div class="float-right"><label class="switch"><input id="chk-fixed" type="checkbox" data-toggle-state="layout-fixed"><span></span></label></div>
                  </div>
                  <div class="clearfix">
                     <p class="float-left">Boxed</p>
                     <div class="float-right"><label class="switch"><input id="chk-boxed" type="checkbox" data-toggle-state="layout-boxed"><span></span></label></div>
                  </div>
                  <div class="clearfix">
                     <p class="float-left">RTL</p>
                     <div class="float-right"><label class="switch"><input id="chk-rtl" type="checkbox"><span></span></label></div>
                  </div>
               </div>
               <div class="p-2">
                  <h4 class="text-muted text-thin">Aside</h4>
                  <div class="clearfix">
                     <p class="float-left">Collapsed</p>
                     <div class="float-right"><label class="switch"><input id="chk-collapsed" type="checkbox" data-toggle-state="aside-collapsed"><span></span></label></div>
                  </div>
                  <div class="clearfix">
                     <p class="float-left">Collapsed Text</p>
                     <div class="float-right"><label class="switch"><input id="chk-collapsed-text" type="checkbox" data-toggle-state="aside-collapsed-text"><span></span></label></div>
                  </div>
                  <div class="clearfix">
                     <p class="float-left">Float</p>
                     <div class="float-right"><label class="switch"><input id="chk-float" type="checkbox" data-toggle-state="aside-float"><span></span></label></div>
                  </div>
                  <div class="clearfix">
                     <p class="float-left">Hover</p>
                     <div class="float-right"><label class="switch"><input id="chk-hover" type="checkbox" data-toggle-state="aside-hover"><span></span></label></div>
                  </div>
                  <div class="clearfix">
                     <p class="float-left">Show Scrollbar</p>
                     <div class="float-right"><label class="switch"><input id="chk-scroll" type="checkbox" data-toggle-state="show-scrollbar" data-target=".sidebar"><span></span></label></div>
                  </div>
               </div>
            </div>
            <div class="tab-pane fade" id="app-chat" role="tabpanel">
               <h3 class="text-center text-thin mt-4">Connections</h3>
               <div class="list-group">
                  <!-- START list title-->
                  <div class="list-group-item border-0"><small class="text-muted">ONLINE</small></div><!-- END list title-->
                  <div class="list-group-item list-group-item-action border-0">
                     <div class="media"><img class="align-self-center mr-3 rounded-circle thumb48" src="/templates/admin/img/user/05.jpg" alt="Image">
                        <div class="media-body text-truncate"><a href="#"><strong>Juan Sims</strong></a><br><small class="text-muted">Designeer</small></div>
                        <div class="ml-auto"><span class="circle bg-success circle-lg"></span></div>
                     </div>
                  </div>
                  <div class="list-group-item list-group-item-action border-0">
                     <div class="media"><img class="align-self-center mr-3 rounded-circle thumb48" src="/templates/admin/img/user/06.jpg" alt="Image">
                        <div class="media-body text-truncate"><a href="#"><strong>Maureen Jenkins</strong></a><br><small class="text-muted">Designeer</small></div>
                        <div class="ml-auto"><span class="circle bg-success circle-lg"></span></div>
                     </div>
                  </div>
                  <div class="list-group-item list-group-item-action border-0">
                     <div class="media"><img class="align-self-center mr-3 rounded-circle thumb48" src="/templates/admin/img/user/07.jpg" alt="Image">
                        <div class="media-body text-truncate"><a href="#"><strong>Billie Dunn</strong></a><br><small class="text-muted">Designeer</small></div>
                        <div class="ml-auto"><span class="circle bg-danger circle-lg"></span></div>
                     </div>
                  </div>
                  <div class="list-group-item list-group-item-action border-0">
                     <div class="media"><img class="align-self-center mr-3 rounded-circle thumb48" src="/templates/admin/img/user/08.jpg" alt="Image">
                        <div class="media-body text-truncate"><a href="#"><strong>Tomothy Roberts</strong></a><br><small class="text-muted">Designeer</small></div>
                        <div class="ml-auto"><span class="circle bg-warning circle-lg"></span></div>
                     </div>
                  </div><!-- START list title-->
                  <div class="list-group-item border-0"><small class="text-muted">OFFLINE</small></div><!-- END list title-->
                  <div class="list-group-item list-group-item-action border-0">
                     <div class="media"><img class="align-self-center mr-3 rounded-circle thumb48" src="/templates/admin/img/user/09.jpg" alt="Image">
                        <div class="media-body text-truncate"><a href="#"><strong>Lawrence Robinson</strong></a><br><small class="text-muted">Designeer</small></div>
                        <div class="ml-auto"><span class="circle bg-warning circle-lg"></span></div>
                     </div>
                  </div>
                  <div class="list-group-item list-group-item-action border-0">
                     <div class="media"><img class="align-self-center mr-3 rounded-circle thumb48" src="/templates/admin/img/user/10.jpg" alt="Image">
                        <div class="media-body text-truncate"><a href="#"><strong>Tyrone Owens</strong></a><br><small class="text-muted">Designeer</small></div>
                        <div class="ml-auto"><span class="circle bg-warning circle-lg"></span></div>
                     </div>
                  </div>
               </div>
               <div class="px-3 py-4 text-center">
                  <!-- Optional link to list more users--><a class="btn btn-purple btn-sm" href="#" title="See more contacts"><strong>Load more..</strong></a>
               </div><!-- Extra items-->
               <div class="px-3 py-2">
                  <p><small class="text-muted">Tasks completion</small></p>
                  <div class="progress progress-xs m-0">
                     <div class="progress-bar bg-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"><span class="sr-only">80% Complete</span></div>
                  </div>
               </div>
               <div class="px-3 py-2">
                  <p><small class="text-muted">Upload quota</small></p>
                  <div class="progress progress-xs m-0">
                     <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"><span class="sr-only">40% Complete</span></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </nav><!-- END Off Sidebar (right)-->
</aside>

app/views/layouts/partials/_sidebar.html.erb
<!-- sidebar-->
<aside class="aside-container">
   <!-- START Sidebar (left)-->
   <div class="aside-inner">
      <nav class="sidebar" data-sidebar-anyclick-close="">
         <!-- START sidebar nav-->
         <ul class="sidebar-nav">
            <!-- START user info-->
            <li class="has-user-block">
               <div class="collapse" id="user-block">
                  <div class="item user-block">
                     <!-- User picture-->
                     <div class="user-block-picture">
                        <div class="user-block-status"><img class="img-thumbnail rounded-circle" src="<%= asset_path("no-user.png")%>" alt="Avatar" width="60" height="60">
                           <div class="circle bg-success circle-lg"></div>
                        </div>
                     </div><!-- Name and Job-->
                     <div class="user-block-info"><span class="user-block-name"><%= current_user.full_name%></span><span class="user-block-role"><%= current_user.role.name%></span></div>
                  </div>
               </div>
            </li><!-- END user info-->
            <!-- Iterates over all sidebar items-->
            <li class="nav-heading "><span data-localize="sidebar.heading.HEADER">Menu Navigation</span></li>
            <li class="<%= check_active(root_path, true)%>"><a href="<%= root_path %>" title="Dashboard"><em class="icon-speedometer"></em><span>Dashboard</span></a></li>
            <%if policy(XmlFile).read?%>
               <li class="<%= check_active('xml_files')%>"><a href="<%= xml_files_path %>" title="XML Files"><em class="fas fa-file"></em><span>XML Files</span></a></li>
            <%end%>
            <%if policy(Part).read?%>
               <li class="<%= check_active(parts_path)%>"><a href="<%= parts_path %>" title="Parts"><em class="fas fa-cogs"></em><span>Parts</span></a></li>
            <%end%>
            <%if policy(BomHeader).read?%>
               <li class="<%= check_active(bom_headers_path)%>"><a href="<%= bom_headers_path %>" title="BOMs"><em class="fas fa-cogs"></em><span>BOMs</span></a></li>
            <%end%>
            <%if policy(Document).read?%>
               <li class="<%= check_active(documents_path)%>"><a href="<%= documents_path %>" title="BOMs"><em class="fas fa-file"></em><span>Documents</span></a></li>
            <%end%>
            <%if policy(Setting).read?%>
               <li class="<%= check_active(settings_path)%>"><a href="<%= settings_path %>" title="Settings"><em class="fas fa-cog"></em><span>Settings</span></a></li>
            <%end%>
            <%if policy(Role).read?%>
               <li class="<%= check_active("roles")%>"><a href="<%= roles_path %>" title="Roles"><em class="fas fa-user-check"></em><span>Roles</span></a></li>
            <%end%>
            <%if policy(User).read?%>
               <li class="<%= check_active("users")%>"><a href="<%= users_path %>" title="Users"><em class="fas fa-users"></em><span>Users</span></a></li>
            <%end%>

         </ul><!-- END sidebar nav-->
      </nav>
   </div><!-- END Sidebar (left)-->
</aside>